fix error printing and abort Threads on exceptions
1. pp was being invoked but not required, so it was failing
2. Because exceptions aren't being raised from Threads, these
   errors were being silently ignore.
3. In general we want exceptions in threads to abort the thread/
   fail the test

It might even be a good idea to have Thread.abort_on_exception = true
in production and not just in tests, but we'll just make this
iterative change for now.

Test output now looks like this. The Es were happening before this
change, the TypeErrors are new.

All these errors will be fixed in a subsequent commit.

.E#<TypeError: no implicit conversion of nil into String>
..E.#<TypeError: no implicit conversion of nil into String>
..

Finished tests in 4.436106s, 1.8034 tests/s, 2.7051 assertions/s.

  1) Error:
test_ez_value_sync(TestStathat):
TypeError: no implicit conversion of nil into String
...

  2) Error:
test_ez_count_sync(TestStathat):
TypeError: no implicit conversion of nil into String
...

8 tests, 12 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/Users/john/80pct/stathat/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib" "/Users/john/80pct/stathat/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/test_stathat.rb" ]
/Users/john/80pct/stathat/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => test
(See full trace by running task with --trace)